name: Go Test

on:
  pull_request:
    branches:
      - main
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres   
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Wait for PostgreSQL to be ready
        run: sleep 10 

      - name: Create Database, User, and Assign Ownership
        env:
          PGPASSWORD: postgres 
        run: |
          psql -U postgres -h 127.0.0.1 -p 5432 -c "CREATE USER ${{ secrets.DB_User }} WITH PASSWORD '${{ secrets.DB_Password }}';"
          
          psql -U postgres -h 127.0.0.1 -p 5432 -c "CREATE DATABASE ${{ secrets.DB_Name }} OWNER ${{ secrets.DB_User }};"

          psql -U postgres -h 127.0.0.1 -p 5432 -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_Name }} To ${{ secrets.DB_User }};"
          
          psql -U postgres -h 127.0.0.1 -p 5432 -c "ALTER DATABASE ${{ secrets.DB_Name }} OWNER TO ${{ secrets.DB_User }};"

      - name: Run Tests
        env:
          DB_User: ${{ secrets.DB_User }}
          DB_Password: ${{ secrets.DB_Password }}
          DB_Name: ${{ secrets.DB_Name }}
          DB_Host: 127.0.0.1
          DB_Port: "5432"
          S3_Bucket_Name: sidd1234
        run: go test ./...
