name: Packer_Validate

on:
  pull_request:
    branches: [main]

jobs:
    packer_validate:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Packer
          uses: hashicorp/setup-packer@main
          id: setup_packer

        - name: Packer Init
          id: init_packer
          run: "packer init ./packer/packer.pkr.hcl"

        - name: Packer fmt
          id: fmt_packer
          run: |
            cd ./packer
            packer fmt -check .
            
        - name: Create .env file
          run: |
            echo "DB_User=${{ secrets.DB_User }}" >> .env
            echo "DB_Password=${{ secrets.DB_Password }}" >> .env
            echo "DB_Name=${{ secrets.DB_Name }}" >> .env
            echo "DB_Host=localhost" >> .env
            echo "DB_Port=5432" >> .env
            
        - name: Packer Validate
          id: validate_packer
          run: |
            set -e
            cd ./packer
            packer validate .