name: Packer Build Workdflow

on:
  push:
    branches: ["main"]

jobs:
    packer-build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Create .env file
            run: |
              echo "DB_User="${{ secrets.DB_User }}"" >> .env
              echo "DB_Password="${{ secrets.DB_Password }}"" >> .env
              echo "DB_Name="${{ secrets.DB_Name }}"" >> .env
              echo "DB_Host="localhost"" >> .env
              echo "DB_Port="${{secrets.DB_PORT}}"" >> .env
              echo "DB_SslMode= "disable"" >> .env
              echo "App_Port=":3000"" >> .env

          - name: Setup Packer
            uses: hashicorp/setup-packer@main
            id: setup_packer
    
          - name: Packer Init
            id: init_packer
            run: "packer init ./packer/packer.pkr.hcl"
          
          - name: AWS Credentials Configuration
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_AMI_REGION}}

          - name: Run Packer Build
            env:
              PKR_VAR_ami_name: ${{ secrets.AMI_NAME }}
              PKR_VAR_instance_type: ${{secrets.AMI_INSTANCE_TYPE}}
              PKR_VAR_ami_region: ${{secrets.AWS_AMI_REGION}}
              PKR_VAR_aws_profile: ${{secrets.AWS_PROFILE}}
              PKR_VAR_source_ami: ${{secrets.SOURCE_AMI}}
              PKR_VAR_ssh_username: ${{secrets.AMI_SSH_USERNAME}}
              PKR_VAR_ami_shared_users: "[${{ secrets.AWS_DEMO_ACCOUNT_ID }}]"
              PKR_VAR_subnet_id: "${{secrets.AWS_SUBNET_ID}}"
            run: |
              GOOS=linux GOARCH=amd64 go build -o webapp main.go

              cd packer
              packer build packer.pkr.hcl

              echo "packer built passed"