name: packer_build

on:
  pull_request: 
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          echo "DB_User=${{ secrets.DB_User }}" >> .env
          echo "DB_Password=${{ secrets.DB_Password }}" >> .env
          echo "DB_Name=${{ secrets.DB_Name }}" >> .env
          echo "DB_Host=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
